PREFIX bc: <https://w3id.org/bncc/comp#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?item ?codigo ?prerequisito ?codigoPrerequisito ?etapa ?escopo ?labelItem ?labelPrerequisito
WHERE {
  ?item bc:temPrerequisitoExplicito ?prerequisito ;
        bc:codigoBNCC ?codigo .
  ?prerequisito bc:codigoBNCC ?codigoPrerequisito .
  OPTIONAL { ?item rdfs:label ?labelItem }
  OPTIONAL { ?prerequisito rdfs:label ?labelPrerequisito }
  OPTIONAL { ?item bc:pertenceEtapa ?etapa }
  OPTIONAL { ?item bc:dirigidoA ?escopo }
}
ORDER BY ?codigo ?codigoPrerequisito
