PREFIX bc: <https://w3id.org/bncc/comp#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Parâmetros:
#   VALUES (?planoSel ?anoSel ?eixoSel) { (bc:PlanoExemploSegurancaEF8 bc:Ano8EF bc:CulturaDigital) }
SELECT DISTINCT ?planoSel ?anoSel ?eixoSel ?conceito ?labelConceito
WHERE {
  VALUES (?planoSel ?anoSel ?eixoSel) { (bc:PlanoExemploSegurancaEF8 bc:Ano8EF bc:CulturaDigital) }

  {
    SELECT DISTINCT ?conceito ?anoSel ?eixoSel
    WHERE {
      ?item a bc:HabilidadeFundamental ;
            bc:dirigidoA ?anoSel .
      FILTER(!BOUND(?eixoSel) || EXISTS { ?item bc:associadoAEixo ?eixoSel })

      {
        ?item bc:abordaConceito ?conceito .
      }
      UNION
      {
        ?item bc:temObjetoConhecimento/bc:representaConceito ?conceito .
      }
    }
  }

  OPTIONAL { ?conceito rdfs:label ?labelConceito }

  FILTER NOT EXISTS {
    ?planoSel bc:cobreConceito/(bc:temSubconceito*) ?conceito .
  }
}
ORDER BY ?labelConceito ?conceito
