PREFIX bc: <https://w3id.org/bncc/comp#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Parâmetros:
#   VALUES (?planoSel ?anoSel ?eixoSel ?conceitoSel) { (bc:PlanoExemploSegurancaEF8 bc:Ano8EF bc:CulturaDigital UNDEF) }
SELECT DISTINCT ?planoSel ?item ?codigo ?conceitoAlvo ?labelConceitoAlvo ?conceitoPrerequisito ?labelConceitoPrerequisito
WHERE {
  VALUES (?planoSel ?anoSel ?eixoSel ?conceitoSel) { (bc:PlanoExemploSegurancaEF8 bc:Ano8EF bc:CulturaDigital UNDEF) }

  ?planoSel bc:implementaItem ?item .
  OPTIONAL { ?item bc:codigoBNCC ?codigo }

  FILTER(!BOUND(?anoSel) || EXISTS { ?item bc:dirigidoA ?anoSel })
  FILTER(!BOUND(?eixoSel) || EXISTS { ?item bc:associadoAEixo ?eixoSel })

  {
    ?item bc:abordaConceito ?conceitoAlvo .
  }
  UNION
  {
    ?item bc:temObjetoConhecimento/bc:representaConceito ?conceitoAlvo .
  }

  ?conceitoAlvo bc:requerConceito+ ?conceitoPrerequisito .

  FILTER(!BOUND(?conceitoSel) || ?conceitoAlvo = ?conceitoSel || ?conceitoPrerequisito = ?conceitoSel)

  OPTIONAL { ?conceitoAlvo rdfs:label ?labelConceitoAlvo }
  OPTIONAL { ?conceitoPrerequisito rdfs:label ?labelConceitoPrerequisito }

  FILTER NOT EXISTS {
    ?planoSel bc:cobreConceito/(bc:temSubconceito*) ?conceitoPrerequisito .
  }
}
ORDER BY ?codigo ?labelConceitoPrerequisito ?conceitoPrerequisito
